# Render Deployment Configuration for React SPA
services:
  - type: web
    name: fund-request-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html